// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvbwalvidzomwmcijxww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2YndhbHZpZHpvbXdtY2lqeHd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MDg1MTksImV4cCI6MjA3MTA4NDUxOX0.JleFBc7RYhUr2RRTlxXZBsfy1uHEYK8YZugOPox1s3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
 
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});